export const FETCH_STORY_IDS_REQUEST = 'FETCH_STORY_IDS_REQUEST';
export const FETCH_STORY_IDS_SUCCESS = 'FETCH_STORY_IDS_SUCCESS';
export const FETCH_STORY_IDS_FAILURE = 'FETCH_STORY_IDS_FAILURE';


export const FETCH_STORIES_REQUEST = 'FETCH_STORIES_REQUEST';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAILURE = 'FETCH_STORIES_FAILURE';

export const FETCH_FILTERED_STORIES = 'FETCH_FILTERED_STORIES';

export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';