export const FETCH_TOPSTORY_IDS_REQUEST = 'FETCH_TOPSTORY_IDS_REQUEST';
export const FETCH_TOPSTORY_IDS_SUCCESS = 'FETCH_TOPSTORY_IDS_SUCCESS';
export const FETCH_TOPSTORY_IDS_FAILURE = 'FETCH_TOPSTORY_IDS_FAILURE';

export const FETCH_BESTSTORY_IDS_REQUEST = 'FETCH_BESTSTORY_IDS_REQUEST';
export const FETCH_BESTSTORY_IDS_SUCCESS = 'FETCH_BESTSTORY_IDS_SUCCESS';
export const FETCH_BESTSTORY_IDS_FAILURE = 'FETCH_BESTSTORY_IDS_FAILURE';

export const FETCH_NEWSTORY_IDS_REQUEST = 'FETCH_NEWSTORY_IDS_REQUEST';
export const FETCH_NEWSTORY_IDS_SUCCESS = 'FETCH_NEWSTORY_IDS_SUCCESS';
export const FETCH_NEWSTORY_IDS_FAILURE = 'FETCH_NEWSTORY_IDS_FAILURE';

export const FETCH_TOPSTORIES_REQUEST = 'FETCH_TOPSTORIES_REQUEST';
export const FETCH_TOPSTORIES_SUCCESS = 'FETCH_TOPSTORIES_SUCCESS';
export const FETCH_TOPSTORIES_FAILURE = 'FETCH_TOPSTORIES_FAILURE';


export const FETCH_BESTSTORIES_REQUEST = 'FETCH_BESTSTORIES_REQUEST';
export const FETCH_BESTSTORIES_SUCCESS = 'FETCH_BESTSTORIES_SUCCESS';
export const FETCH_BESTSTORIES_FAILURE = 'FETCH_BESTSTORIES_FAILURE';


export const FETCH_NEWSTORIES_REQUEST = 'FETCH_NEWSTORIES_REQUEST';
export const FETCH_NEWSTORIES_SUCCESS = 'FETCH_NEWSTORIES_SUCCESS';
export const FETCH_NEWSTORIES_FAILURE = 'FETCH_NEWSTORIES_FAILURE';

export const FETCH_FILTERED_STORIES = 'FETCH_FILTERED_STORIES';

export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';